### ISSUE TITLE
Test assigning Item Set(s) and Site(s) to collection items on import

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/FedoraConnector#45]
For both the item sets and sites chosen select box on the Fedora Connector import form, please verify:

- Sites select box is pre-populated with all sites that have 'Auto Assign New Items' checked in Site Admin Settings
- Choosing multiple sets/sites and importing new collection results in sets/sites assigned within collection item's metadata
- Choosing different sites/sets and importing to update (i.e. previously imported) collection results in new sets/sites assigned within item metadata, and does not remove previously assigned sets/sites

I've been using UC Davis' Fedora instance Sherry Lehmann collection to test https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005, but feel free to test with another instance. Thanks!

**Comment by katknow** [comment]
Just wanted to provide an update--I'm having trouble getting the module to work at all, but I'm trying to figure it out so I can complete the testing. I think my PHP is okay (I populated my site via the Omeka2Importer). I keep getting stuck on in-progress, and it doesn't seem to be moving past the 2nd or 3rd item.

**Comment by matthewjmckinley** [comment]
Hi Katherine, I assume you are testing on the entire Fedora collection https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005 -- could you test one of the child containers such as https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d77p4p to see if that works?

I'm able to import the entire collection in my instance, but it does take about 10-20 minutes to complete since it's so large--a smaller import should give much quicker results.

Also, are there any other errors or info being reported in application.log ?

**Comment by katknow** [comment]
Okay, the big one is still in progress and the child container is an error, so perhaps there is some kind of path error? My application.log is empty, so I don't know if there is a problem there too...

**Comment by katknow** [comment]
This is from my attempt to do child that I accessed via the specific attempt page:

2021-12-03T20:52:53+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekapMn4Uv.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:52:53+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekakVi8Ct[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekapMn4Uv.jpg'" failed with status code 1.
2021-12-03T20:54:14+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekazFlvuA.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:14+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekauDp7F0[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekazFlvuA.jpg'" failed with status code 1.
2021-12-03T20:54:14+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaftLWZL.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:14+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaMQ0Hka[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaftLWZL.jpg'" failed with status code 1.
2021-12-03T20:54:15+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekazDRjd1.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:15+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekayQaJGn[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekazDRjd1.jpg'" failed with status code 1.
2021-12-03T20:54:16+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekatLWr1j.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:16+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekasmCpLE[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekatLWr1j.jpg'" failed with status code 1.
2021-12-03T20:54:16+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekalgpwzG.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:16+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaCo3ojZ[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekalgpwzG.jpg'" failed with status code 1.
2021-12-03T20:54:17+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaHHMwe7.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:17+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omeka06zvRn[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaHHMwe7.jpg'" failed with status code 1.
2021-12-03T20:54:18+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaTOs7QB.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:18+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaOfa7CQ[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaTOs7QB.jpg'" failed with status code 1.
2021-12-03T20:54:18+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekafqO0aa.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:18+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaWZ7B6m[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekafqO0aa.jpg'" failed with status code 1.
2021-12-03T20:54:19+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekadx8l9L.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:19+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omeka08t1iX[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekadx8l9L.jpg'" failed with status code 1.
2021-12-03T20:54:20+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekad8PNDr.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:20+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaKQyc1A[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekad8PNDr.jpg'" failed with status code 1.
2021-12-03T20:54:20+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaVfD0Ia.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:20+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaWCudii[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaVfD0Ia.jpg'" failed with status code 1.
2021-12-03T20:54:21+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omeka1K2VsX.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:21+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaYfkub3[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omeka1K2VsX.jpg'" failed with status code 1.
2021-12-03T20:54:22+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaxIIRVN.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:22+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaAfRULR[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaxIIRVN.jpg'" failed with status code 1.
2021-12-03T20:54:22+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omeka9O9BZH.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:22+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekawJuq7J[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omeka9O9BZH.jpg'" failed with status code 1.
2021-12-03T20:54:23+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekalHShtF.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:23+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaId4sTF[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekalHShtF.jpg'" failed with status code 1.
2021-12-03T20:54:24+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omekaETgEaJ.jpg' @ error/convert.c/ConvertImageCommand/3235.

2021-12-03T20:54:24+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekadFqDfG[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaETgEaJ.jpg'" failed with status code 1.
2021-12-03T20:54:24+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php:626
Errors:
{
    "o:media": [
        {
            "file": [
                "Error validating \"\/fcrepo\/rest\/collection\/sherry-lehmann\/D-005\/d77p4p\/media\/text\/d77p4p-015.txt\". Cannot store files with the media type \"text\/x-c\"."
            ]
        }
    ]
}
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php(318): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#1 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#2 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#3 /var/www/html/katknow/OmekaSTesting/modules/FedoraConnector/src/Job/Import.php(115): Omeka\Api\Manager->create('items', Array)
#4 /var/www/html/katknow/OmekaSTesting/modules/FedoraConnector/src/Job/Import.php(151): FedoraConnector\Job\Import->importContainer('https://digital...')
#5 /var/www/html/katknow/OmekaSTesting/modules/FedoraConnector/src/Job/Import.php(151): FedoraConnector\Job\Import->importContainer('https://digital...')
#6 /var/www/html/katknow/OmekaSTesting/modules/FedoraConnector/src/Job/Import.php(48): FedoraConnector\Job\Import->importContainer('https://digital...')
#7 /var/www/html/katknow/OmekaSTesting/application/src/Job/DispatchStrategy/Synchronous.php(34): FedoraConnector\Job\Import->perform()
#8 /var/www/html/katknow/OmekaSTesting/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#9 /var/www/html/katknow/OmekaSTesting/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#10 {main}

**Comment by matthewjmckinley** [comment]
When I check `import files into Omeka S`, I see similar `/usr/bin/convert` errors--I suspect that's an issue with Imagemagick somehow, and will look into it. However, the Fedora item import still eventually completes.

I suspect it's that final error that is causing the failure. You might need to add `text/x-c` to your "allowed file extensions" under the global Omeka S settings, like John mentions here: https://forum.omeka.org/t/omeka-api-import-error/9725/3

Though it's strange because my settings do not have that specific extension, just standard txt, and the import still works.

**Comment by katknow** [comment]
So, I added the text/x-c and it didn't seem to do anything, but when I uncheck import files into Omeka S I am able to fully import everything and it did update the few items that made it through earlier. I tested everything above and in my case as long as I don't check that box everything works as you described.

**Comment by matthewjmckinley** [comment]
Well, that's good for the purpose of this issue! Would you mind creating a separate issue within this FedoraConnector repo for that bug with the relevant log posted above? Thanks!
