### ISSUE TITLE
Job with "error" worked (sort of)

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/FedoraConnector#47]
Job with "error" status (and lots of errors in the log) shows as "0 added" and yet added 200+ items to my site.

Imports page looks like this:
![fedora](https://user-images.githubusercontent.com/28012148/228671847-01129ac7-e53d-41df-840b-2cdd47224e7a.PNG)

Job ID looks like this:

![fedora2](https://user-images.githubusercontent.com/28012148/228671860-e232630e-5763-4f1f-8131-77ab5e21c433.PNG)

Items added are 296; they look like this:

![fedora3](https://user-images.githubusercontent.com/28012148/228671872-0eb6e2b2-4b0e-4884-b549-50986348a319.PNG)

Error log looks like this:

> 2023-03-28T13:21:30+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
> convert: no images defined `/tmp/omekazoysKJ.jpg' @ error/convert.c/ConvertImageCommand/3235.
> 
> 2023-03-28T13:21:30+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaho8N61[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekazoysKJ.jpg'" failed with status code 1.
> 2023-03-28T13:24:08+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
> convert: no images defined `/tmp/omeka1sjIsW.jpg' @ error/convert.c/ConvertImageCommand/3235.
> 2023-03-28T13:24:08+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaZY4KXg[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omeka1sjIsW.jpg'" failed with status code 1.

.... (after 200+ of those errors) ....

> 2023-03-28T14:20:41+00:00 ERR (3): convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/564.
convert: no images defined `/tmp/omeka76P7m8.jpg' @ error/convert.c/ConvertImageCommand/3235.
> 2023-03-28T14:20:41+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekanvAtb7[0]' -auto-orient -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omeka76P7m8.jpg'" failed with status code 1.
> 2023-03-28T14:20:41+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:654
> Errors:
> {
>     "o:media": [
>         {
>             "file": [
>                 "Error validating \"\/fcrepo\/rest\/collection\/sherry-lehmann\/D-005\/d7f598\/media\/text\/d7f598-016.txt\". Cannot store files with the media type \"application\/octet-stream\"."
>             ]
>         },
>         {
>             "file": [
>                 "Error validating \"\/fcrepo\/rest\/collection\/sherry-lehmann\/D-005\/d7f598\/media\/text\/d7f598-019.txt\". Cannot store files with the media type \"application\/octet-stream\"."
>             ]
>         }
>     ]
> }
> Stack trace:
> #0 /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(346): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
> #1 /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
> #2 /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
> #3 /var/www/html/amayer/amayer-s/omeka-s/modules/FedoraConnector/src/Job/Import.php(115): Omeka\Api\Manager->create('items', Array)
> #4 /var/www/html/amayer/amayer-s/omeka-s/modules/FedoraConnector/src/Job/Import.php(151): FedoraConnector\Job\Import->importContainer('https://digital...')
> #5 /var/www/html/amayer/amayer-s/omeka-s/modules/FedoraConnector/src/Job/Import.php(151): FedoraConnector\Job\Import->importContainer('https://digital...')
> #6 /var/www/html/amayer/amayer-s/omeka-s/modules/FedoraConnector/src/Job/Import.php(151): FedoraConnector\Job\Import->importContainer('https://digital...')
> #7 /var/www/html/amayer/amayer-s/omeka-s/modules/FedoraConnector/src/Job/Import.php(48): FedoraConnector\Job\Import->importContainer('https://digital...')
> #8 /var/www/html/amayer/amayer-s/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): FedoraConnector\Job\Import->perform()
> #9 /var/www/html/amayer/amayer-s/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
> #10 /var/www/html/amayer/amayer-s/omeka-s/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
> #11 {main}

As I think we've talked about before, an "error" somewhere in the process shouldn't really show as an error unless the process has stopped. And the "Total: XXX" link should work if any items are added regardless of that error status. This would also improve with a smaller test batch because then you could see how the metadata mismatch is happening (missing Title values; importing each item four times, twice with media and twice without; skipping item IDs strangely; and other assorted questionable behaviour).

**Comment by allanaaa** [comment]
When I say each item is imported four times, this is what I mean:

It seems to be picking up a parent node, and some children nodes, creating items in some cases, and then I think some of the error messages are coming from other children with files it can't accept (TXT):

![four1](https://user-images.githubusercontent.com/28012148/228674132-9e4ac52d-e057-4fb8-bb61-d8e81d8d85c4.PNG)
![four2](https://user-images.githubusercontent.com/28012148/228674138-a676ac26-1f16-4b09-963f-56adc9510225.PNG)
![four3](https://user-images.githubusercontent.com/28012148/228674139-542d52f3-0cc6-4002-9427-af8cd19c7c2b.PNG)
![four4](https://user-images.githubusercontent.com/28012148/228674140-197c2ea9-b27d-4e4f-89cf-399344b0fb29.PNG)

The parent node in this case: 
https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media

Reflects 6 children: 

        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/dngs
        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/text
        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/page_images
        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/d7f598.pdf
        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/d7f598.txt
        https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/D-005/d7f598/media/images

It's pulling the PDF and TXT onto the parent item (item ID 7069) and all the /images onto another (item 7073). And a node of /page_images that has no files associated to it at the source, and then the DNGs item which also has no files associated but I assume would have thrown up an error if it had.

**Comment by matthewjmckinley** [comment]
This should hopefully be fixed with the recent FedoraConnector import refactoring. But also Fedora can be weird and hard to predict. Please let me know if this error or a similar one persists!
